export const RD_PROVINCES = [
  "Distrito Nacional",
  "Santo Domingo",
  "Santiago",
  "La Vega",
  "San Cristóbal",
  "Puerto Plata",
  "San Pedro de Macorís",
  "Duarte",
  "La Altagracia",
  "La Romana",
  "Espaillat",
  "Azua",
  "Barahona",
  "Monseñor Nouel",
  "Peravia",
  "Sánchez Ramírez",
  "Valverde",
  "María Trinidad Sánchez",
  "Hermanas Mirabal",
  "Monte Plata",
  "Hato Mayor",
  "El Seibo",
  "Samaná",
  "Bahoruco",
  "Independencia",
  "Pedernales",
  "San Juan",
  "Elías Piña",
  "Dajabón",
  "Monte Cristi",
  "Santiago Rodríguez",
  "San José de Ocoa",
] as const;

export const CONDITIONS = [
  "Diabetes tipo 1",
  "Diabetes tipo 2",
  "Hipertensión arterial",
  "Enfermedad cardíaca",
  "Enfermedad de la tiroides",
  "Cáncer (actual o previo)",
  "Pancreatitis",
  "Cálculos biliares",
  "Enfermedad renal",
  "Enfermedad hepática",
  "Trastorno alimentario",
  "Depresión o ansiedad",
  "Reflujo (ERGE) severo",
  "Ninguna de las anteriores",
] as const;

export const BP_RANGES = [
  { id: "normal", label: "Normal", desc: "Menor a 120/80", color: "oklch(0.62 0.13 160)" },
  { id: "elevated", label: "Elevada", desc: "120–129 / menor a 80", color: "oklch(0.78 0.14 75)" },
  { id: "high1", label: "Alta — Etapa 1", desc: "130–139 / 80–89", color: "oklch(0.7 0.18 50)" },
  { id: "high2", label: "Alta — Etapa 2", desc: "140+ / 90+", color: "oklch(0.6 0.21 27)" },
  { id: "unknown", label: "No la sé", desc: "Está bien, lo revisamos juntos", color: "oklch(0.5 0.03 250)" },
] as const;

export const TOTAL_STEPS = 6;
